### ISSUE TITLE
total lack of documentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blast#4]
There's not a lot going on in this sim. But there are some bits that should be documented, like:

• The purpose for each screen
• What and why for ItemModel.step  (apparently something to do with memory profiling, according to the commit message)
• What and why for BlastModel.step (apparently an animating particle/rectangle, according to the commit message. but why?)

Seems like it would have been pretty easy to do all of the above when the code was created.

**Comment by pixelzoom** [comment]
Assigned to @jbphet since he added the 2nd screen and made the most recent commits.

**Comment by jbphet** [comment]
The sim was created by @samreid, and I simply made it possible to have two screens that are essentially the same instead of one since two screens were needed for testing of memory leak issues, see https://github.com/phetsims/tasks/issues/546.  Assigning to @samreid to add the documentation that @pixelzoom feels is lacking.

**Comment by pixelzoom** [comment]
> I simply made it possible to have two screens that are essentially the same instead of one since two screens were needed for testing of memory leak issues, see phetsims/tasks#546.

A comment to that effect in the source code would have made this issue unnecessary.

**Comment by pixelzoom** [comment]
Addressed in #3. Closing.
